# File: docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: favorites_web
    ports:
      - "9030:80"
    volumes:
      # 앱 소스코드 마운트
      - ./app:/var/www/html
      # 새로운 이미지 저장 경로를 컨테이너의 /var/www/html/images 폴더와 연결
      - /volume1/docker/woos_webs/favorites-docker/app/images:/var/www/html/images
    networks:
      - web_services_network

networks:
  web_services_network:
    external: true